server:
  port: 8080

spring:
  application:
    name: markdown-reader
  web:
    resources:
      static-locations: classpath:/static/
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

# 应用配置
app:
  # 笔记文件夹
  biji-folder: biji
